### ISSUE TITLE
Diagrama de clases-Alvaro Froylan Pacheco Osorio-Antonia Martinez Sandoval

### ISSUE THREAD

**Issue by Alvaro2-0** [SistemasTecTlaxiaco/actividad-6-diagrama-de-clases-mextlaxs#1]
[DIAGRAMA DE CLASES-ALVARO-ANTONIA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-diagrama-de-clases-mextlaxs/files/14728023/DIAGRAMA.DE.CLASES-ALVARO-ANTONIA.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...falta el codigo en assembly
Calificación 17
